-- Traduccion por Jonathan

-- Subnames

UPDATE creature_template SET subname = 'Maestro de Establos' WHERE subname = 'Stable Master';
UPDATE creature_template SET subname = 'Instructor de alquimia' WHERE subname = 'Alchemy Trainer';
UPDATE creature_template SET subname = 'Instructor de arqueología' WHERE subname = 'Archaeology Trainer';
UPDATE creature_template SET subname = 'Maestro de batalla de arena' WHERE subname = 'Arena Battlemaster';
UPDATE creature_template SET subname = 'Instructor de guerreros' WHERE subname = 'Warrior Trainer';
UPDATE creature_template SET subname = 'Instructor de brujos' WHERE subname = 'Warlock Trainer';
UPDATE creature_template SET subname = 'Jefe de Guerra' WHERE subname = 'Warchief';
UPDATE creature_template SET subname = 'Objetos comerciables' WHERE subname = 'Trade Goods';
UPDATE creature_template SET subname = 'Instructor de sastrería' WHERE subname = 'Tailoring Trainer';
UPDATE creature_template SET subname = 'Suministros de sastrería' WHERE subname = 'Tailoring Supplies';
UPDATE creature_template SET subname = 'Vendedor de Tabardos' WHERE subname = 'Tabard Vendor';
UPDATE creature_template SET subname = 'Instructor de desuello' WHERE subname = 'Skinning Trainer';
UPDATE creature_template SET subname = 'Instructor de Chamanes' WHERE subname = 'Shaman Trainer';
UPDATE creature_template SET subname = 'Instructora de pícaros' WHERE subname = 'Rogue Trainer';
UPDATE creature_template SET subname = 'Instructor de profesión' WHERE subname = 'Profession Trainer';
UPDATE creature_template SET subname = 'Instructor de sacerdotes' WHERE subname = 'Priest Trainer';
UPDATE creature_template SET subname = 'Sacerdote' WHERE subname = 'Priest';
UPDATE creature_template SET subname = 'Instructor de mascotas' WHERE subname = 'Pet Trainer';
UPDATE creature_template SET subname = 'Instructor de paladines' WHERE subname = 'Paladin Trainer';
UPDATE creature_template SET subname = 'Instructor de mineria' WHERE subname = 'Mining Trainer';
UPDATE creature_template SET subname = 'Suministros de mineria' WHERE subname = 'Mining Supplies';
UPDATE creature_template SET subname = 'Maestro de armas' WHERE subname = 'Master of Arms';
UPDATE creature_template SET subname = 'Instructor de magos' WHERE subname = 'Mage Trainer';
UPDATE creature_template SET subname = 'Rey de Ventormenta' WHERE subname = 'King of Stormwind';
UPDATE creature_template SET subname = 'Tabernero' WHERE subname = 'Innkeeper';
UPDATE creature_template SET subname = 'Instructor de cazadores' WHERE subname = 'Hunter Trainer';
UPDATE creature_template SET subname = 'Instructor de herboristeria' WHERE subname = 'Herbalism Trainer';
UPDATE creature_template SET subname = 'Maestro de grifos' WHERE subname = 'Gryphon Master';
UPDATE creature_template SET subname = 'Suministros Comerciales' WHERE subname = 'Trade Supplies';
UPDATE creature_template SET subname = 'Instructor de Equitación' WHERE subname = 'Riding Trainer';
UPDATE creature_template SET subname = 'Instructor de portales' WHERE subname = 'Portal Trainer';
UPDATE creature_template SET subname = 'Suministros de venenos' WHERE subname = 'Poison Supplies';
UPDATE creature_template SET subname = 'Forjador de armas' WHERE subname = 'Weaponsmith';
UPDATE creature_template SET subname = 'Martillo Crepuscular' WHERE subname = "Twilight's Hammer";
UPDATE creature_template SET subname = 'Comerciante' WHERE subname = 'Tradesman';
UPDATE creature_template SET subname = 'Guardia de Ventormenta' WHERE subname = 'Stormwind City Guard';
UPDATE creature_template SET subname = 'Intendente de Ventormenta' WHERE subname = 'Stormwind Quartermaster';
UPDATE creature_template SET subname = 'Componentes' WHERE subname = 'Reagents';
UPDATE creature_template SET subname = 'Suministros de componentes' WHERE subname = 'Reagent Supplies';
UPDATE creature_template SET subname = 'Principe de Ventormenta' WHERE subname = 'Prince of Stormwind';
UPDATE creature_template SET subname = 'Venenos y componentes' WHERE subname = 'Poisons & Reagents';
UPDATE creature_template SET subname = 'Maestro instructor de sastrería' WHERE subname = 'Master Tailoring Trainer';
UPDATE creature_template SET subname = 'Mercader de armaduras de malla' WHERE subname = 'Mail Armor Merchant';
UPDATE creature_template SET subname = 'Instructor de herrería' WHERE subname = 'Blacksmithing Trainer';
UPDATE creature_template SET subname = 'Fabricante de armaduras y escudos' WHERE subname = 'Armorer & Shieldcrafter';
UPDATE creature_template SET subname = 'Mercader de armaduras de tela y cuero' WHERE subname = 'Cloth & Leather Armor Merchant';
UPDATE creature_template SET subname = 'Panadera ambulante' WHERE subname = 'Traveling Baker';
UPDATE creature_template SET subname = 'Medico' WHERE subname = 'Physician';
UPDATE creature_template SET subname = 'Suminisros Generales' WHERE subname = 'General Supplies';
UPDATE creature_template SET subname = 'Carnicero' WHERE subname = 'Butcher';
UPDATE creature_template SET subname = 'Cocinero' WHERE subname = 'Cook';
UPDATE creature_template SET subname = 'Guardia Real de Ventormenta' WHERE subname = 'Stormwind Royal Guard';
UPDATE creature_template SET subname = 'Instructor de druidas' WHERE subname = 'Druid Trainer';
UPDATE creature_template SET subname = 'Suministros de Alquimia' WHERE subname = 'Alchemy Supplies';
UPDATE creature_template SET subname = 'Suministros de alquimia y componentes' WHERE subname = 'Alchemy Supplies & Reagents';
UPDATE creature_template SET subname = 'Intendente de género de la Alianza' WHERE subname = 'Alliance Cloth Quartermaster';
UPDATE creature_template SET subname = 'Aprendiz de Alquimia' WHERE subname = 'Apprentice Alchemist';
UPDATE creature_template SET subname = 'Aprendiz de Herreria' WHERE subname = 'Apprentice Blacksmith';
UPDATE creature_template SET subname = 'Aprendiz de Encantamiento' WHERE subname = 'Apprentice Enchanter';



-- NPC's ===============================================================================================================

UPDATE creature_template SET name = 'Alguacil McBride' WHERE name = 'Marshal McBride';
UPDATE creature_template SET name = 'Huarguerrero Roca Negra' WHERE entry = '49871';
UPDATE creature_template SET name = 'Soldado de infantería de Ventormenta herido' WHERE entry = '50047';
UPDATE creature_template SET name = 'Infantería de Ventormenta' WHERE entry = '49869';
UPDATE creature_template SET subname = 'Alto comandante de la defensa de Ventormenta' WHERE name = 'General Marcus Jonathan';
UPDATE creature_template SET name = 'Espía Roca Negra' WHERE name = 'Blackrock Spy';
UPDATE creature_template SET name = 'Asesino goblin' WHERE name = 'Goblin Assassin';
UPDATE creature_template SET name = 'Guardia de Ventormenta' WHERE name = 'Stormwind Guard';
UPDATE creature_template SET name = 'Guardia de Ventormenta' WHERE name = 'Stormwind City Guard';
UPDATE creature_template SET name = 'Patrullero de Ventormenta' WHERE name = 'Stormwind City Patroller';
UPDATE creature_template SET name = 'Invasor Roca Negra' WHERE entry = '42937';
UPDATE creature_template SET name = 'Kurtok el Destripador' WHERE entry = '42938';
UPDATE creature_template SET name = 'Guardia de Villanorte' WHERE entry = '1642';
UPDATE creature_template SET name = 'Campesino de Villanorte' WHERE entry = '11260';
UPDATE creature_template SET name = 'Dragonizo mecánico de mitril' WHERE name = 'Mithril Mechanical Dragonling';
UPDATE creature_template SET name = 'Araña del bosque' WHERE name = 'Forest Spider';
UPDATE creature_template SET name = 'Matón Defias' WHERE name = 'Defias Thug';
UPDATE creature_template SET name = 'Alguacil Dughan' WHERE name = 'Marshal Dughan';
UPDATE creature_template SET name = 'Remy "Dos Veces"' WHERE name = 'Remy "Two Times"';
UPDATE creature_template SET name = 'Guardia Thomas' WHERE name = 'Guard Thomas';
UPDATE creature_template SET name = 'Caballo marrón' WHERE name = 'Brown Horse';
UPDATE creature_template SET name = 'Mariscal Haggard' WHERE name = 'Marshal Haggard';
UPDATE creature_template SET name = 'Dientes de Oro' WHERE name = 'Goldtooth';
UPDATE creature_template SET name = 'Gallina' WHERE name = 'Chicken';
UPDATE creature_template SET name = 'Araña de mina' WHERE name = 'Mine Spider';
UPDATE creature_template SET name = 'Bandido Defias' WHERE name = 'Defias Bandit';
UPDATE creature_template SET name = 'Subastador Beardo' WHERE name = 'Auctioneer Beardo';
UPDATE creature_template SET name = 'Subastador Buckler' WHERE name = 'Auctioneer Buckler';
UPDATE creature_template SET name = 'Subastador Cain' WHERE name = 'Auctioneer Cain';
UPDATE creature_template SET name = 'Subastador Cazarez' WHERE name = 'Auctioneer Cazarez';
UPDATE creature_template SET name = 'Subastador Chilton' WHERE name = 'Auctioneer Chilton';
UPDATE creature_template SET name = 'Subastador Epitwee' WHERE name = 'Auctioneer Epitwee';
UPDATE creature_template SET name = 'Subastador Fitch' WHERE name = 'Auctioneer Fitch';
UPDATE creature_template SET name = 'Subastador Golothas' WHERE name = 'Auctioneer Golothas';
UPDATE creature_template SET name = 'Subastador Graves' WHERE name = 'Auctioneer Graves';
UPDATE creature_template SET name = 'Subastador Grimful' WHERE name = 'Auctioneer Grimful';
UPDATE creature_template SET name = 'Subastador Grizzlin' WHERE name = 'Auctioneer Grizzlin';
UPDATE creature_template SET name = 'Subastador Gullem' WHERE name = 'Auctioneer Gullem';
UPDATE creature_template SET name = 'Subastador Jaxon' WHERE name = 'Auctioneer Jaxon';
UPDATE creature_template SET name = 'Subastador Kresky' WHERE name = 'Auctioneer Kresky';
UPDATE creature_template SET name = 'Subastador Leeka' WHERE name = 'Auctioneer Leeka';
UPDATE creature_template SET name = 'Subastador Lympkin' WHERE name = 'Auctioneer Lympkin';
UPDATE creature_template SET name = 'Subastador Naxxremis' WHERE name = 'Auctioneer Naxxremis';
UPDATE creature_template SET name = "Subastador O'reely" WHERE name = "Auctioneer O'reely";
UPDATE creature_template SET name = 'Subastador Redmuse' WHERE name = 'Auctioneer Redmuse';
UPDATE creature_template SET name = 'Subastador Rhyker' WHERE name = 'Auctioneer Rhyker';
UPDATE creature_template SET name = "Subastador Silva'las" WHERE name = "Auctioneer Silva'las";
UPDATE creature_template SET name = 'Subastador Stampi' WHERE name = 'Auctioneer Stampi';
UPDATE creature_template SET name = 'Subastador Stockton' WHERE name = 'Auctioneer Stockton';
UPDATE creature_template SET name = 'Subastador Thathung' WHERE name = 'Auctioneer Thathung';
UPDATE creature_template SET name = 'Subastador Tolon' WHERE name = 'Auctioneer Tolon';
UPDATE creature_template SET name = 'Subastador Tricket' WHERE name = 'Auctioneer Tricket';
UPDATE creature_template SET name = 'Subastador Wabang' WHERE name = 'Auctioneer Wabang';
UPDATE creature_template SET name = 'Subastador Yarly' WHERE name = 'Auctioneer Yarly';
UPDATE creature_template SET name = 'Hermano Daniels' WHERE name = 'Brother Daniels';
UPDATE creature_template SET name = 'Hermano Kristoff' WHERE name = 'Brother Kristoff';
UPDATE creature_template SET name = 'Hermano Malach' WHERE name = 'Brother Malach';
UPDATE creature_template SET name = 'Hermano Neals' WHERE name = 'Brother Neals';
UPDATE creature_template SET name = 'Hermano Nimetz' WHERE name = 'Brother Nimetz';
UPDATE creature_template SET name = 'Hermano Ravenoak' WHERE name = 'Brother Ravenoak';
UPDATE creature_template SET name = 'Hermano Sarno' WHERE name = 'Brother Sarno';
UPDATE creature_template SET name = 'Oso marrón' WHERE name = 'Brown Bear';
UPDATE creature_template SET name = 'Elekk marrón' WHERE name = 'Brown Elekk';
UPDATE creature_template SET name = 'Kodo marrón' WHERE name = 'Brown Kodo';
UPDATE creature_template SET name = 'Marmota marrón' WHERE name = 'Brown Marmot';
UPDATE creature_template SET name = 'Perro de la pradera marrón' WHERE name = 'Brown Prairie Dog';


-- Gossip_menu_option ==================================================================================================

UPDATE gossip_menu_option SET option_text = 'Permiteme ver tus mercancias' WHERE option_text = 'Let me browse your goods.';
UPDATE gossip_menu_option SET option_text = 'Un entrenador de clase' WHERE option_text = 'A class trainer';
UPDATE gossip_menu_option SET option_text = 'Un maestro de profesión' WHERE option_text = 'A profession trainer';
UPDATE gossip_menu_option SET option_text = 'Alquimia' WHERE option_text = 'Alchemy';
UPDATE gossip_menu_option SET option_text = 'Laboratorio de alquimia' WHERE option_text = 'Alchemy Lab';
UPDATE gossip_menu_option SET option_text = 'Casa de subastas' WHERE option_text = 'Auction House';
UPDATE gossip_menu_option SET option_text = 'Subasta!' WHERE option_text = 'Auction!';
UPDATE gossip_menu_option SET option_text = 'Hacha' WHERE option_text = 'Axe';
UPDATE gossip_menu_option SET option_text = 'Atrás' WHERE option_text = 'Back..';
UPDATE gossip_menu_option SET option_text = 'Banco' WHERE option_text = 'Bank';
UPDATE gossip_menu_option SET option_text = 'Banco de Forjaz' WHERE option_text = 'Bank of Ironforge';
UPDATE gossip_menu_option SET option_text = 'Banco de Ventormenta' WHERE option_text = 'Bank of Stormwind';
UPDATE gossip_menu_option SET option_text = 'Peluquero' WHERE option_text = 'Barber';
UPDATE gossip_menu_option SET option_text = 'Maestro de batalla' WHERE option_text = 'Battlemaster';
UPDATE gossip_menu_option SET option_text = 'Herrería' WHERE option_text = 'Blacksmithing';
UPDATE gossip_menu_option SET option_text = 'Entrenador de Clase' WHERE option_text = 'Class Trainer';
UPDATE gossip_menu_option SET option_text = 'Cocina' WHERE option_text = 'Cooking';
UPDATE gossip_menu_option SET option_text = 'Druida' WHERE option_text = 'Druid';
UPDATE gossip_menu_option SET option_text = 'Encantamiento' WHERE option_text = 'Enchanting';
UPDATE gossip_menu_option SET option_text = 'Ingeniería' WHERE option_text = 'Engineering';
UPDATE gossip_menu_option SET option_text = 'Primeros Auxilios' WHERE option_text = 'First Aid';
UPDATE gossip_menu_option SET option_text = 'Pesca' WHERE option_text = 'Fishing';
UPDATE gossip_menu_option SET option_text = 'Maestro de Vuelo' WHERE option_text = 'Flight Master';
UPDATE gossip_menu_option SET option_text = 'Maestro de Hermandad' WHERE option_text = 'Guild Master';
UPDATE gossip_menu_option SET option_text = 'Herboristeria' WHERE option_text = 'Herbalism';
UPDATE gossip_menu_option SET option_text = 'Cazador' WHERE option_text = 'Hunter';
UPDATE gossip_menu_option SET option_text = 'Yo quiero ver tus mercancias' WHERE option_text = 'I want to browse your goods';
UPDATE gossip_menu_option SET option_text = 'Chamán' WHERE option_text = 'Shaman';
UPDATE gossip_menu_option SET option_text = 'Pícaro' WHERE option_text = 'Rogue';
UPDATE gossip_menu_option SET option_text = 'Sacerdote' WHERE option_text = 'Priest';
UPDATE gossip_menu_option SET option_text = 'Mineria' WHERE option_text = 'Mining';
UPDATE gossip_menu_option SET option_text = 'Convierte esta posada como tu hogar.' WHERE option_text = 'Make this inn your home.';
UPDATE gossip_menu_option SET option_text = 'Casilla de correo' WHERE option_text = 'Mailbox';
UPDATE gossip_menu_option SET option_text = 'Mago' WHERE option_text = 'Mage';
UPDATE gossip_menu_option SET option_text = 'Peletería' WHERE option_text = 'Leatherworking';
UPDATE gossip_menu_option SET option_text = 'Inscripción' WHERE option_text = 'Inscription';
UPDATE gossip_menu_option SET option_text = 'Posada' WHERE option_text = 'Inn';
UPDATE gossip_menu_option SET option_text = 'Me gustaria entrenar.' WHERE option_text = 'I would like to train.';
UPDATE gossip_menu_option SET option_text = 'Arco' WHERE option_text = 'Bow';
UPDATE gossip_menu_option SET option_text = 'Podrias darme una dirección?' WHERE option_text = 'Can you give me directions?';
UPDATE gossip_menu_option SET option_text = 'Me gustaría ver tus mercancias.' WHERE option_text = 'I want to browse your goods.';
UPDATE gossip_menu_option SET option_text = 'Ya veo.' WHERE option_text = 'I see.';
UPDATE gossip_menu_option SET option_text = 'Como puedo formar una hermandad?' WHERE option_text = 'How do I form a guild?';
UPDATE gossip_menu_option SET option_text = 'Arma de Fuego' WHERE option_text = 'Gun';
UPDATE gossip_menu_option SET option_text = 'Entrename.' WHERE option_text = 'Train me.';
UPDATE gossip_menu_option SET option_text = 'Entrename!' WHERE option_text = 'Train me!';
UPDATE gossip_menu_option SET option_text = 'Deseo olvidar mis talentos' WHERE option_text = 'I wish to unlearn my talents';
UPDATE gossip_menu_option SET option_text = 'Guerrero' WHERE option_text = 'Warrior';
UPDATE gossip_menu_option SET option_text = 'Maestro de establos' WHERE option_text = 'The stable master';
UPDATE gossip_menu_option SET option_text = 'Sastrería' WHERE option_text = 'Tailoring';
UPDATE gossip_menu_option SET option_text = 'Desuello' WHERE option_text = 'Skinning';
UPDATE gossip_menu_option SET option_text = 'Me gustaría poner en el establo a mi mascota.' WHERE option_text = "I'd like to stable my pet here.";
UPDATE gossip_menu_option SET option_text = 'Continuar lectura...' WHERE option_text = 'Continue reading...';
UPDATE gossip_menu_option SET option_text = 'Ballesta' WHERE option_text = 'Crossbow';
UPDATE gossip_menu_option SET option_text = 'Comida y bebida' WHERE option_text = 'Food & Drink';
UPDATE gossip_menu_option SET option_text = 'Maestro de Establos' WHERE option_text = 'Stable Master';
UPDATE gossip_menu_option SET option_text = 'Espada' WHERE option_text = 'Sword';
UPDATE gossip_menu_option SET option_text = 'La Casa de Subastas' WHERE option_text = 'The auction house';
UPDATE gossip_menu_option SET option_text = 'Maestro de grifos' WHERE option_text = 'Gryphon Master';
UPDATE gossip_menu_option SET option_text = 'Maestro de la batalla de la Alianza' WHERE option_text = 'Alliance Battlemasters';