ALTER TABLE `account_data` 
CHANGE `account` `account` INT(10) UNSIGNED DEFAULT '0' NOT NULL, 
CHANGE `type` `type` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL, 
CHANGE `time` `time` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `data` `data` BLOB NOT NULL;

ALTER TABLE `addons` 
ROW_FORMAT=DEFAULT,
CHANGE `crc` `crc` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `arena_team` 
CHANGE `name` `name` VARCHAR(24) NOT NULL,
CHANGE `EmblemStyle` `EmblemStyle` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `BorderStyle` `BorderStyle` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `auctionhouse`
CHANGE `id` `id` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `auctioneerguid` `auctioneerguid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `itemguid` `itemguid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `itemowner` `itemowner` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `buyoutprice` `buyoutprice` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `time` `time` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `buyguid` `buyguid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `lastbid` `lastbid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `startbid` `startbid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `deposit` `deposit` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `addons` ROW_FORMAT=DEFAULT;
ALTER TABLE `channels`
ROW_FORMAT=DEFAULT,
CHANGE `BannedList` `BannedList` TEXT,
DROP PRIMARY KEY, 
ADD PRIMARY KEY (`m_name`, `m_team`);

ALTER TABLE `character_account_data`
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `type` `type` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `time` `time` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `data` `data` BLOB NOT NULL;

ALTER TABLE `character_achievement`
CHANGE `guid` `guid` INT(10) UNSIGNED NOT NULL,
CHANGE `achievement` `achievement` SMALLINT(5) UNSIGNED NOT NULL,
CHANGE `date` `date` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_achievement_progress`
CHANGE `guid` `guid` INT(10) UNSIGNED NOT NULL,
CHANGE `criteria` `criteria` SMALLINT(5) UNSIGNED NOT NULL,
CHANGE `counter` `counter` INT(10) UNSIGNED NOT NULL,
CHANGE `date` `date` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_action`
ROW_FORMAT=DEFAULT,
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `action` `action` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_arena_stats`
ENGINE=InnoDB,
CHANGE `slot` `slot` TINYINT(3) NOT NULL;

ALTER TABLE `character_aura`
ROW_FORMAT=DEFAULT,
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL COMMENT 'Global Unique Identifier',
CHANGE `spell` `spell` MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_banned`
ROW_FORMAT=DEFAULT,
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL COMMENT 'Account id',
CHANGE `bandate` `bandate` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `unbandate` `unbandate` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `active` `active` TINYINT(3) UNSIGNED DEFAULT '1' NOT NULL;

ALTER TABLE `character_battleground_data`
ROW_FORMAT=DEFAULT,
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL COMMENT 'Global Unique Identifier',
CHANGE `instance_id` `instance_id` INT(10) UNSIGNED NOT NULL, 
CHANGE `team` `team` SMALLINT(5) UNSIGNED NOT NULL,
CHANGE `join_map` `join_map` SMALLINT(5) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `taxi_start` `taxi_start` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `taxi_end` `taxi_end` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `mount_spell` `mount_spell` MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_battleground_random`
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_declinedname`
ROW_FORMAT=DEFAULT,
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL COMMENT 'Global Unique Identifier';

ALTER TABLE `character_equipmentsets`
CHANGE `guid` `guid` INT(10) DEFAULT '0' NOT NULL,
CHANGE `setindex` `setindex` TINYINT(3) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `name` `name` VARCHAR(31) NOT NULL,
CHANGE `item0` `item0` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item1` `item1` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item2` `item2` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item3` `item3` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item4` `item4` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item5` `item5` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item6` `item6` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item7` `item7` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item8` `item8` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item9` `item9` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item10` `item10` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item11` `item11` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item12` `item12` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item13` `item13` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item14` `item14` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item15` `item15` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item16` `item16` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item17` `item17` INT(10) UNSIGNED NOT NULL DEFAULT '0', 
CHANGE `item18` `item18` INT(10) UNSIGNED NOT NULL DEFAULT '0';

ALTER TABLE `character_gifts`
CHANGE `guid` `guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `item_guid` `item_guid` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `entry` `entry` INT(10) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `flags` `flags` INT(10) UNSIGNED DEFAULT '0' NOT NULL;

ALTER TABLE `character_glyphs`
CHANGE `guid` `guid` INT(10) UNSIGNED NOT NULL,
CHANGE `glyph1` `glyph1` SMALLINT(5) UNSIGNED DEFAULT '0' NOT NULL,
CHANGE `glyph2` `glyph2` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph3` `glyph3` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph4` `glyph4` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph5` `glyph5` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph6` `glyph6` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph7` `glyph7` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ,
CHANGE `glyph8` `glyph8` SMALLINT(5) UNSIGNED DEFAULT '0' NULL ;