
#ifndef DEF_THE_STONECORE_H
#define DEF_THE_STONECORE_H

enum Creatures
{
    // Boss
	CREATURE_CORBORUS               = 43438,
    CREATURE_SLAPHIDE               = 43214,
    CREATURE_OZRUK                  = 42188,
    CREATURE_HIGH_PRIESTESS_AZIL    = 42333,

	// Trash npc
    CREATURE_CRYSTALSPAWN_GIANT                         = 42810,
	CREATURE_IMP										= 43014,
	CREATURE_MILLHOUSE_MANASTORM						= 43391,
	CREATURE_ROCK_BORER									= 43917,
	CREATURE_ROCK_BORER2								= 42845,
	CREATURE_STONECORE_BERSERKER						= 43430,
	CREATURE_STONECORE_BRUISER							= 42692,
	CREATURE_STONECORE_EARTHSHAPER						= 43537,
	CREATURE_STONECORE_FLAYER							= 42808,
	CREATURE_MAGMALORD									= 42789,
	CREATURE_RIFT_CONJURER								= 42691,
	CREATURE_STONECORE_SENTRY							= 42695,
	CREATURE_STONECORE_WARBRINGER						= 42696,
};

enum Data
{
	DATA_CORBORUS_EVENT,
    DATA_SLAPHIDE_EVENT,
    DATA_OZRUK_EVENT,
    DATA_HIGH_PRIESTESS_AZIL_EVENT,
};

enum Data64
{
	DATA_CORBORUS,
    DATA_SLAPHIDE,
    DATA_OZRUK,
    DATA_HIGH_PRIESTESS_AZIL,
};

#endif