ALTER TABLE `quest_template` ADD (`RewSkillLineId` int(11) unsigned NOT NULL DEFAULT '0' AFTER `OfferRewardEmoteDelay4`,
                                  `RewSkillPoints` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewSkillLineId`,
                                  `RewRepMask` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewSkillPoints`,
                                  `QuestGiverPortrait` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewRepMask`,
                                  `QuestTurnInPortrait` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestGiverPortrait`,
                                  `RewCurrencyId1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestTurnInPortrait`,
                                  `RewCurrencyCount1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId1`,
                                  `RewCurrencyId2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount1`,
                                  `RewCurrencyCount2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId2`,
                                  `RewCurrencyId3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount2`,
                                  `RewCurrencyCount3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId3`,
                                  `RewCurrencyId4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount3`,
                                  `RewCurrencyCount4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyId4`,
                                  `ReqCurrencyId1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `RewCurrencyCount4`,
                                  `ReqCurrencyCount1` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId1`,
                                  `ReqCurrencyId2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount1`,
                                  `ReqCurrencyCount2` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId2`,
                                  `ReqCurrencyId3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount2`,
                                  `ReqCurrencyCount3` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId3`,
                                  `ReqCurrencyId4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyCount3`,
                                  `ReqCurrencyCount4` int(11) unsigned NOT NULL DEFAULT '0' AFTER `ReqCurrencyId4`,
                                  `QuestGiverPortraitText` text DEFAULT NULL AFTER `ReqCurrencyCount4`,
                                  `QuestGiverPortraitUnk` text DEFAULT NULL AFTER `QuestGiverPortraitText`,
                                  `QuestTurnInPortraitText` text DEFAULT NULL AFTER `QuestGiverPortraitUnk`,
                                  `QuestTurnInPortraitUnk` text DEFAULT NULL AFTER `QuestTurnInPortraitText`,
                                  `SoundAccept` int(11) unsigned NOT NULL DEFAULT '0' AFTER `QuestTurnInPortraitUnk`,
                                  `SoundTurnIn` int(11) unsigned NOT NULL DEFAULT '0' AFTER `SoundAccept`,
                                  `RequiredSpell` int(11) unsigned NOT NULL DEFAULT '0' AFTER `SoundTurnIn`);