REVOKE ALL PRIVILEGES ON * . * FROM 'cactusemu'@'localhost';
REVOKE ALL PRIVILEGES ON `world` . * FROM 'cactusemu'@'localhost';
REVOKE GRANT OPTION ON `world` . * FROM 'cactusemu'@'localhost';
REVOKE ALL PRIVILEGES ON `characters` . * FROM 'cactusemu'@'localhost';
REVOKE GRANT OPTION ON `characters` . * FROM 'cactusemu'@'localhost';
REVOKE ALL PRIVILEGES ON `auth` . * FROM 'cactusemu'@'localhost';
REVOKE GRANT OPTION ON `auth` . * FROM 'cactusemu'@'localhost';
DROP USER 'cactusemu'@'localhost';
DROP DATABASE IF EXISTS `world`;
DROP DATABASE IF EXISTS `characters`;
DROP DATABASE IF EXISTS `auth`;
