SET @ver=14333;
insert ignore into `emuopcodes`(`version`,`name`,`number`,`type`) values ( @ver,'MSG_OPCODE_UNKNOWN','0','msg');
UPDATE emuopcodes SET number = 50983 WHERE name = "SMSG_CHAR_ENUM" and version = @ver;
UPDATE emuopcodes SET number = 4305 WHERE name = "CMSG_PLAYER_LOGIN" and version = @ver;
UPDATE emuopcodes SET number = 61990 WHERE name = "CMSG_CHAR_ENUM" and version = @ver;
UPDATE emuopcodes SET number = 47735 WHERE name = "SMSG_LOGIN_VERIFY_WORLD" and version = @ver;
UPDATE emuopcodes SET number = 8033 WHERE name = "SMSG_FEATURE_SYSTEM_STATUS" and version = @ver;
UPDATE emuopcodes SET number = 32294 WHERE name = "SMSG_BINDPOINTUPDATE" and version = @ver;
UPDATE emuopcodes SET number = 63011 WHERE name = "SMSG_CORPSE_RECLAIM_DELAY" and version = @ver;
UPDATE emuopcodes SET number = 32439 WHERE name = "SMSG_INIT_WORLD_STATES" and version = @ver;
UPDATE emuopcodes SET number = 3216 WHERE name = "SMSG_PONG" and version = @ver;
UPDATE emuopcodes SET number = 57919 WHERE name = "SMSG_COMPRESSED_UPDATE_OBJECT" and version = @ver;
-- next 9 are from RealmConnection__MessageHandler
UPDATE emuopcodes SET number = 48891 WHERE name = "SMSG_AUTH_RESPONSE" and version = @ver;
UPDATE emuopcodes SET number = 27310 WHERE name = "SMSG_ADDON_INFO" and version = @ver;
UPDATE emuopcodes SET number = 41527 WHERE name = "SMSG_CLIENTCACHE_VERSION" and version = @ver;
UPDATE emuopcodes SET number = 25274 WHERE name = "SMSG_LOGOUT_RESPONSE" and version = @ver;
UPDATE emuopcodes SET number = 15926 WHERE name = "SMSG_CHAR_CREATE" and version = @ver;
UPDATE emuopcodes SET number = 41599 WHERE name = "SMSG_LOGOUT_COMPLETE" and version = @ver;
UPDATE emuopcodes SET number = 43575 WHERE name = "SMSG_LOGOUT_CANCEL_ACK" and version = @ver;
UPDATE emuopcodes SET number = 16122 WHERE name = "SMSG_CHAR_DELETE" and version = @ver;
UPDATE emuopcodes SET number = 45795 WHERE name = "SMSG_CHARACTER_LOGIN_FAILED" and version = @ver;

UPDATE emuopcodes SET number = 29435 WHERE name = "CMSG_CAST_SPELL" and version = @ver;
UPDATE emuopcodes SET number = 48874 WHERE name = "CMSG_CANCEL_AURA" and version = @ver;
UPDATE emuopcodes SET number = 22965 WHERE name = "CMSG_MESSAGECHAT_SAY" and version = @ver;
UPDATE emuopcodes SET number = 61990 WHERE name = "CMSG_READY_FOR_ACCOUNT_DATA_TIMES" and version = @ver;
UPDATE emuopcodes SET number = 4241 WHERE name = "CMSG_CHAR_ENUM" and version = @ver;

UPDATE emuopcodes SET number = 45734 WHERE name = "CMSG_LOGOUT_REQUEST" and version = @ver;
UPDATE emuopcodes SET number = 6369 WHERE name = "MSG_MOVE_START_FORWARD" and version = @ver;
UPDATE emuopcodes SET number = 10467 WHERE name = "MSG_MOVE_SET_WALK_MODE" and version = @ver;
UPDATE emuopcodes SET number = 10346 WHERE name = "MSG_MOVE_STOP" and version = @ver;
UPDATE emuopcodes SET number = 2147 WHERE name = "MSG_MOVE_START_BACKWARD" and version = @ver;
UPDATE emuopcodes SET number = 2122 WHERE name = "MSG_MOVE_START_TURN_LEFT" and version = @ver;
UPDATE emuopcodes SET number = 14434 WHERE name = "MSG_MOVE_START_STRAFE_LEFT" and version = @ver;
UPDATE emuopcodes SET number = 35040 WHERE name = "MSG_MOVE_START_TURN_RIGHT" and version = @ver;
UPDATE emuopcodes SET number = 14442 WHERE name = "MSG_MOVE_JUMP" and version = @ver;
UPDATE emuopcodes SET number = 35041 WHERE name = "MSG_MOVE_FALL_LAND" and version = @ver;
UPDATE emuopcodes SET number = 21313 WHERE name = "MSG_MOVE_SET_PITCH" and version = @ver;

UPDATE emuopcodes SET number = 46706 WHERE name = "CMSG_REQUEST_RAID_INFO" and version = @ver;
UPDATE emuopcodes SET number = 15087 WHERE name = "CMSG_NPC_TEXT_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 32310 WHERE name = "CMSG_PETITION_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 42687 WHERE name = "CMSG_DANCE_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 63022 WHERE name = "CMSG_ARENA_TEAM_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 29286 WHERE name = "CMSG_NAME_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 48702 WHERE name = "CMSG_PET_NAME_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 41578 WHERE name = "CMSG_GUILD_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 62207 WHERE name = "CMSG_PAGE_TEXT_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 11006 WHERE name = "CMSG_QUEST_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 15102 WHERE name = "CMSG_GAMEOBJECT_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 42594 WHERE name = "CMSG_CREATURE_QUERY" and version = @ver;
UPDATE emuopcodes SET number = 32503 WHERE name = "CMSG_ITEM_NAME_QUERY" and version = @ver;